version: '3'
services:
  mmock:
    image: jordimartin/mmock
    container_name: mmock
    restart: always
    ports:
      - "8082:8082"
      - "8083:8083"
    volumes:
      - ./mmock-requests/:/config/